version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb

  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
    depends_on:
      - redis
